openaiApiKey: not-an-actual-password

chat:
  port: 7024
  externalPort: 7024
  ingress:
    enabled: true

    # add external hostname
    hostname: a2rchi.foo.edu
    tls:
      enabled: true
      # TLS for above hostname
      secretName: a2rchi-foo-edu-els

  # add chat image that a2rchi built
  image: localregistry.foo.edu/a2rchi-chat:latest
chromadb:
  # add chat image that a2rchi built  
  image: localregistry.foo.edu/chromadb:latest

uploader:
  image: localregistry.foo.edu/a2rchi-uploader:latest
  port: 5001
  externalPort: 5001

postgresql:
  global:
    security:
      allowInsecureImages: true
  auth:
    existingSecret: "{{ .Release.Name }}-postgresql-password"
    username: a2rchi
    database: a2rchi
  enabled: true
  primary:
    initdb:
      scriptsConfigMap: "{{ .Release.Name }}-init-sql"
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  volumePermissions:
    containerSecurityContext:
      runAsUser: auto  
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
    image:
      repository: bitnami/postgres-exporter
      tag: 0.17.1-debian-12-r12
      pullPolicy: Always
prompt:
  main: |
    You are a conversational chatbot named A2rchi who helps people navigate a computing cluster named SubMIT.
    You will be provided context to help you answer their questions. Using your Linux and computing knowledge,
    answer the question at the end. Unless otherwise indicated, assume the users are not well versed in
    computing. Please do not assume that SubMIT machines have anything installed on top of native Linux except
    if the context mentions it. If you don't know, say "I don't know", if you need to ask a follow up question, please do.

    Context: {context}
    Question: {question}
    
    Helpful Answer:
    

  condense: |
    Given the following conversation between you (the AI named A2rchi), a human user who needs help, and an expert, and a follow up question,
    rephrase the follow up question to be a standalone question, in its original language.
    
    Chat History:
    {chat_history}
    Follow Up Input: {question}
    Standalone question:

weblists:
  miscellanea.list:
    - https://physics.mit.edu/faculty/christoph-paus
    
ollama:
  url: "https://ollama.foo.com"
