{{- if .Values.chat.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 300s
  labels:
    app: {{ include "a2rchi.fullname" . }}-chat
  name: {{ include "a2rchi.fullname" . }}-chat
spec:
  rules:
  - host: {{ .Values.chat.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "a2rchi.fullname" . }}-chat
            port: 
              name: chat-port
        pathType: ImplementationSpecific
  {{- if .Values.chat.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.chat.ingress.hostname }}
    secretName: {{ .Values.chat.ingress.tls.secretName }}
  {{- end }}
{{- end }}
