apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "a2rchi.fullname" . }}-prompt-config
data:
  main.prompt: |-
{{ .Values.prompt.main | indent 4}}

  condense.prompt: |-
{{ .Values.prompt.condense | indent 4}}
    
  
