{{- if .Values.uploader.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ include "a2rchi.fullname" . }}-uploader
  name: {{ include "a2rchi.fullname" . }}-uploader
spec:
  rules:
  - host: {{ .Values.uploader.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "a2rchi.fullname" . }}-uploader
            port:
              name: uploader-port
        pathType: ImplementationSpecific
  {{- if .Values.uploader.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.uploader.ingress.hostname }}
    secretName: {{ .Values.uploader.ingress.tls.secretName }}
  {{- end }}
{{- end }}
