apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "a2rchi.fullname" . }}-weblists
data:
{{- range $name, $urls := .Values.weblists }}
  {{ $name }}: |
{{- range $url := $urls }}
    {{ $url }}
{{- end }}
{{- end }}

